process.on('uncaughtException', function (error) {
    console.log(error);
});
