process.on('uncaughtException', (err) => {
    if (err) console.log(err);
});
